# Generated by Django 5.0 on 2024-11-22 20:01

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[users.validators.validate_name, django.core.validators.MinLengthValidator(3)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[users.validators.validate_name, django.core.validators.MinLengthValidator(3)], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_username, django.core.validators.MinLengthValidator(3)], verbose_name='Username'),
        ),
    ]
